# Project information
site_name: Albumentations Documentation
site_description: Albumentations provides a comprehensive, high-performance framework for augmenting images to improve machine learning models. Ideal for computer vision applications, supporting a wide range of augmentations.
repo_url: https://github.com/albumentations-team/albumentations
site_url: https://albumentations.ai/docs/
edit_uri: edit/master/docs/src/docs/

# Repository
repo_name: albumentations

# Build directory
site_dir: site

# Configuration
theme:
  name: material
  palette:
    primary: white
    accent: white
  custom_dir: custom_theme/
  logo: images/logo.png
  favicon: images/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    # Navigation
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.prune
    # Search
    - search.suggest
    - search.highlight
    - search.share
    # TOC
    - toc.follow
    - toc.integrate

# Plugins (ordered for optimal processing)
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: false
            show_if_no_docstring: false
            show_object_full_path: true
          parsing:
            paths:
              - /albumentations
          selection:
            docstring_style: google
            docstring_options:
              replace_admonitions: false
      custom_templates: mkdocstrings_theme
  - awesome-pages
  - mkdocs-simple-hooks:
      hooks:
        on_pre_page: "albumentations_docs.hooks:on_pre_page"
        on_page_content: "albumentations_docs.hooks:on_page_content"
        on_nav: "albumentations_docs.hooks:on_nav"
  - macros:
      modules:
        - albumentations_docs.main
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

# Extensions
markdown_extensions:
  # Code highlighting
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  # General formatting
  - attr_list
  - admonition
  - tables
  - toc:
      permalink: true
  # PyMdown extensions
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.critic:
      mode: view

extra_css:
  - css/extra.css

# Additional assets
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/MathJax.js?config=TeX-MML-AM_CHTML
  - js/extra.js

# Extra features
extra:
  notebook_github_uri: https://github.com/albumentations-team/albumentations_examples/blob/main/notebooks/
  notebook_colab_uri: https://colab.research.google.com/github/albumentations-team/albumentations_examples/blob/main/notebooks/
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_ID, '']
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/albumentations
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/100504475/
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/AKPrrDYNAt
  generator: false
