
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_code_formatting_types:
    name: Check code formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install dev requirements
      run: pip install pre-commit
    - name: Run checks
      run: pre-commit run --files $(find mkdocs -type f)
