name: Build GitHub Pages

on:
  push:
    branches: main
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          path: gh_pages
          ref: gh-pages

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build documentation
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          NODE_ENV: production
          BUILD_DIR: ${GITHUB_WORKSPACE}/gh_pages
        run: |
          # Build both website and docs
          make prod

      - name: Generate sitemap
        run: |
          pip install lxml
          python tools/generate_sitemap.py ${GITHUB_WORKSPACE}/gh_pages

      - name: Commit and push changes
        run: |
          cd ${GITHUB_WORKSPACE}/gh_pages
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Build $(date +"%Y-%m-%d %H:%M:%S"). ${GITHUB_SHA::8}. Event: ${GITHUB_EVENT_NAME}."
          git push origin gh-pages
